### ISSUE TITLE
Merge with original addon?

### ISSUE THREAD

**Issue by xcasxcursex** [TheGoddessInari/netflix-1080p-firefox#4]
Hi there, first off thanks for the addon :) 

I used to use the original https://github.com/vladikoff/netflix-1080p-firefox but I haven't needed it recently as simply spoofing the useragent was doing the trick... until recent days where I got the 'endlessly loading spinner' thing. 
So, I went looking for the addon and found this one, not realising it was forked. I read in the issues of the original, that it was removed as it had shipped containing netflix's JS. I can only assume you've resolved that matter.

Is it time for a merge?

**Comment by TheGoddessInari** [comment]
Nobody's contacted me regarding the addon from anywhere else.

At this point, it's been nearly entirely rewritten to satisfy [Mozilla Addon Policies](https://extensionworkshop.com/documentation/publish/add-on-policies/).

I'm content to keep maintaining this since it's no longer dependent on deobfuscation. This makes it easy to update to new playercore versions.

**Comment by xcasxcursex** [comment]
Oh well too late now, I guess. Shame :(
